# Generated by Django 5.2.7 on 2025-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
