# Generated by Django 5.2.7 on 2025-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_discount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
