# Generated by Django 5.2.7 on 2025-10-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
